/**
 * 刷新类型脚本 - 只更新类型定义，不覆盖已有代码
 * 
 * 使用场景：
 * - 已经编辑了 custom.ts 或 custom.css
 * - 需要更新类型定义以匹配 custom.html 中的控件
 * 
 * 执行内容：
 * - 从 src/custom.html 解析控件
 * - 更新 src/custom-types.d.ts
 * - 更新 src/custom.ts 头部的控件注释（保留用户代码）
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

const CONTROL_TAG_MAP = {
  'a-text': 'TextControl',
  'a-textarea': 'TextareaControl',
  'a-date': 'DateControl',
  'a-number': 'NumberControl',
  'a-radio': 'RadioControl',
  'a-checkbox': 'CheckboxControl',
  'a-dropdown': 'DropdownControl',
  'a-dropdown-multi': 'DropdownMultiControl',
  'a-logic': 'LogicControl',
  'a-attachment': 'AttachmentControl',
  'a-image': 'AttachmentControl',
  'a-signature': 'SignatureControl',
  'a-location': 'LocationControl',
  'a-user-selector': 'StaffControl',
  'a-user-multi-selector': 'StaffControl',
  'a-departmentselector': 'DeptControl',
  'a-departmentmultiselector': 'DeptControl',
  'a-staffDeptMixed': 'StaffDeptMixedControl',
  'a-sheet': 'SheetControl',
  'a-create-by': 'CreateByControl',
  'a-created-time': 'CreatedTimeControl',
  'a-sequence-no': 'SequenceNoControl',
  'a-relevance-form': 'RelevanceFormControl',
};

/**
 * 提取控件信息（用于生成类型）
 */
function extractControls(html) {
  const topLevelControls = [];
  const sheetControls = {};

  const sheetRegex = /<a-sheet\s+[^>]*key="([^"]+)"[^>]*>([\s\S]*?)<\/a-sheet>/gi;
  let sheetMatch;

  while ((sheetMatch = sheetRegex.exec(html)) !== null) {
    const sheetKey = sheetMatch[1];
    const sheetContent = sheetMatch[2];
    sheetControls[sheetKey] = [];

    const fullSheetTag = sheetMatch[0];
    const dataNameMatch = /data-name="([^"]*)"/.exec(fullSheetTag);
    const sheetDataName = dataNameMatch ? dataNameMatch[1] : '';
    topLevelControls.push({ key: sheetKey, tagName: 'a-sheet', typeClass: 'SheetControl', dataName: sheetDataName });

    const tagRegex = /<([a-z-]+)\s+[^>]*key="([^"]+)"[^>]*data-name="([^"]*)"[^>]*>/gi;
    let tagMatch;
    while ((tagMatch = tagRegex.exec(sheetContent)) !== null) {
      const tagName = tagMatch[1].toLowerCase();
      const key = tagMatch[2];
      const dataName = tagMatch[3];
      const typeClass = CONTROL_TAG_MAP[tagName];
      if (typeClass) {
        sheetControls[sheetKey].push({ key, tagName, typeClass, dataName });
      }
    }
  }

  const htmlWithoutSheets = html.replace(/<a-sheet\s+[^>]*>[\s\S]*?<\/a-sheet>/gi, '');

  const tagRegex = /<([a-z-]+)\s+[^>]*key="([^"]+)"[^>]*data-name="([^"]*)"[^>]*>/gi;
  let tagMatch;
  while ((tagMatch = tagRegex.exec(htmlWithoutSheets)) !== null) {
    const tagName = tagMatch[1].toLowerCase();
    const key = tagMatch[2];
    const dataName = tagMatch[3];
    const typeClass = CONTROL_TAG_MAP[tagName];
    if (typeClass) {
      topLevelControls.push({ key, tagName, typeClass, dataName });
    }
  }

  return { topLevelControls, sheetControls };
}

/**
 * 生成 custom-types.d.ts
 */
function generateCustomTypes(topLevelControls, sheetControls) {
  const sheetKeys = Object.keys(sheetControls);

  const controlEntries = topLevelControls.map(c => {
    const comment = c.dataName ? `  /** ${c.dataName} */\n  ` : '  ';
    if (sheetKeys.includes(c.key)) {
      return `${comment}${c.key}: SheetControl<${c.key}Data>;`;
    }
    return `${comment}${c.key}: ${c.typeClass};`;
  }).join('\n');

  let sheetTypes = '';
  for (const [sheetKey, controls] of Object.entries(sheetControls)) {
    const sheetEntries = controls.map(c => {
      const comment = c.dataName ? `  /** ${c.dataName} */\n  ` : '  ';
      return `${comment}${c.key}: ${c.typeClass};`;
    }).join('\n');
    const dataEntries = controls.map(c => {
      const comment = c.dataName ? `  /** ${c.dataName} */\n  ` : '  ';
      return `${comment}${c.key}: ${c.typeClass} extends { value: infer V } ? V : any;`;
    }).join('\n');
    sheetTypes += `\ninterface ${sheetKey}Columns {\n${sheetEntries}\n}\n`;
    sheetTypes += `\ntype ${sheetKey}Data = {\n${dataEntries}\n};\n`;
  }

  return `// Auto-generated by refresh-types.mjs - DO NOT EDIT MANUALLY
// Generated at: ${new Date().toISOString()}

interface FormControls {
${controlEntries}
}
${sheetTypes}
`;
}

/**
 * 更新 custom.ts 的头部注释，保留用户代码
 */
function updateCustomTsHeader(existingContent, topLevelControls, sheetControls) {
  const typeNames = {
    'TextControl': '短文本',
    'TextareaControl': '长文本',
    'DateControl': '日期',
    'NumberControl': '数值',
    'RadioControl': '单选框',
    'CheckboxControl': '复选框',
    'DropdownControl': '下拉单选',
    'DropdownMultiControl': '下拉多选',
    'LogicControl': '逻辑',
    'AttachmentControl': '附件/图片',
    'SignatureControl': '手写签名',
    'LocationControl': '位置/地址',
    'StaffControl': '人员选择',
    'DeptControl': '部门选择',
    'StaffDeptMixedControl': '混合选人',
    'SheetControl': '子表',
    'CreateByControl': '创建人',
    'CreatedTimeControl': '创建时间',
    'SequenceNoControl': '单据号',
    'TitleControl': '标题',
    'RelevanceFormControl': '关联表单',
  };

  const controlComments = topLevelControls
    .filter(c => !c.key.startsWith('creater') && c.key !== 'createdTime' && c.key !== 'sequenceNo' && c.key !== 'title1')
    .map(c => {
      const typeName = typeNames[c.typeClass] || c.typeClass;
      const name = c.dataName ? ` (${c.dataName}/${typeName})` : ` (${typeName})`;
      return ` * - ${c.key}${name}`;
    }).join('\n');

  let sheetComments = '';
  for (const [sheetKey, controls] of Object.entries(sheetControls)) {
    const sheetName = topLevelControls.find(c => c.key === sheetKey)?.dataName || sheetKey;
    sheetComments += `\n * 子表 "${sheetName}" 的列:\n`;
    sheetComments += controls.map(c => {
      const typeName = typeNames[c.typeClass] || c.typeClass;
      const name = c.dataName ? ` (${c.dataName}/${typeName})` : ` (${typeName})`;
      return ` * - ${c.key}${name}`;
    }).join('\n');
  }

  const newHeader = `/// <reference path="../types/index.d.ts" />
/// <reference path="custom-types.d.ts" />

/**
 * 云枢表单自定义代码
 * 
 * 关联文件: custom.html, custom.css
 * 
 * 使用说明:
 * - 使用 tsc 编译此文件，或手动转换为 JS
 * - 复制编译后的 JS 代码到云枢平台的 JS 编辑窗口
 * 
 * 可用控件:
${controlComments}${sheetComments}
 */`;

  // 查找用户代码的起始位置（跳过头部注释）
  const codeStartMatch = existingContent.match(/\/\*\*[\s\S]*?\*\/\s*/);
  
  if (codeStartMatch) {
    // 找到注释结束位置，保留后面的用户代码
    const userCodeStart = codeStartMatch.index + codeStartMatch[0].length;
    const userCode = existingContent.substring(userCodeStart);
    return newHeader + '\n\n' + userCode;
  }
  
  // 如果找不到注释，保留原内容
  return newHeader + '\n\n// ========== 用户代码 ==========\n' + existingContent;
}

function main() {
  const customHtmlPath = join(rootDir, 'src', 'custom.html');

  if (!existsSync(customHtmlPath)) {
    console.error('错误: 找不到 src/custom.html');
    console.error('请先运行 npm run extract 从 template.html 生成初始文件');
    process.exit(1);
  }

  const html = readFileSync(customHtmlPath, 'utf-8');

  // 提取控件信息
  const { topLevelControls, sheetControls } = extractControls(html);
  console.log(`发现 ${topLevelControls.length} 个顶层控件:`);
  topLevelControls.forEach(c => console.log(`  - ${c.key} (${c.dataName || c.typeClass})`));

  for (const [sheetKey, controls] of Object.entries(sheetControls)) {
    console.log(`\n子表 "${sheetKey}" 包含 ${controls.length} 个列:`);
    controls.forEach(c => console.log(`  - ${c.key} (${c.dataName || c.typeClass})`));
  }

  const srcDir = join(rootDir, 'src');

  // 1. 更新 custom-types.d.ts
  const customTypes = generateCustomTypes(topLevelControls, sheetControls);
  writeFileSync(join(srcDir, 'custom-types.d.ts'), customTypes, 'utf-8');
  console.log('\n✓ 已更新 src/custom-types.d.ts');

  // 2. 更新 custom.ts 的头部注释（保留用户代码）
  const customTsPath = join(srcDir, 'custom.ts');
  if (existsSync(customTsPath)) {
    const existingTs = readFileSync(customTsPath, 'utf-8');
    const updatedTs = updateCustomTsHeader(existingTs, topLevelControls, sheetControls);
    writeFileSync(customTsPath, updatedTs, 'utf-8');
    console.log('✓ 已更新 src/custom.ts 的控件注释（保留用户代码）');
  } else {
    console.warn('⚠ src/custom.ts 不存在，跳过更新');
  }

  // 3. 不更新 custom.css - 用户自己维护

  console.log('\n========================================');
  console.log('类型刷新完成！');
  console.log('========================================');
  console.log('更新的文件:');
  console.log('  src/custom-types.d.ts - 类型定义');
  console.log('  src/custom.ts         - 控件注释（保留用户代码）');
  console.log('');
  console.log('未修改:');
  console.log('  src/custom.css        - 用户自己维护');
  console.log('========================================');
}

main();